# Generated by Django 5.2.5 on 2025-12-01 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0005_curso_disciplinas_curso_turma_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=200)),
                ('integrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.curso')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.turma')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.tipoeventos')),
            ],
        ),
    ]
