# Generated by Django 5.2.5 on 2025-12-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoeventos',
            name='superior',
            field=models.BooleanField(default=False),
        ),
    ]
