# Generated by Django 5.2.5 on 2025-12-01 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_curso_disciplinas_curso_turma_curso'),
        ('calendario', '0002_tipoeventos_superior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.curso'),
        ),
        migrations.AlterField(
            model_name='event',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.turma'),
        ),
    ]
