# Generated by Django 5.2.5 on 2025-12-01 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_remove_event_end_time_remove_event_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='event',
            name='data_inicio',
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='calendario.event')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
