# Generated by Django 5.2.5 on 2025-11-29 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('posicao', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=20)),
                ('Endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('posicao', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=20)),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=20)),
                ('quantidade_aulas', models.PositiveIntegerField()),
                ('horas_aula', models.PositiveIntegerField()),
                ('horas_relogio', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=20)),
                ('dias_proibidos', models.ManyToManyField(to='cadastro.diasemana')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=20)),
                ('dias_proibidos', models.ManyToManyField(to='cadastro.diasemana')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('capacidade', models.PositiveIntegerField(blank=True, null=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.predio')),
            ],
        ),
        migrations.AddField(
            model_name='diasemana',
            name='tempos',
            field=models.ManyToManyField(to='cadastro.tempo'),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveIntegerField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.disciplinas')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.professor')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.sala')),
                ('tempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.tempo')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('aulas', models.ManyToManyField(to='cadastro.aula')),
                ('dias_proibidos', models.ManyToManyField(to='cadastro.diasemana')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=20)),
                ('turmas', models.ManyToManyField(to='cadastro.turma')),
            ],
        ),
    ]
