# Generated by Django 5.2.5 on 2025-11-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempo',
            options={'ordering': ['posicao']},
        ),
        migrations.RemoveField(
            model_name='turma',
            name='dias_proibidos',
        ),
        migrations.CreateModel(
            name='DiaTempoPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.diasemana')),
                ('tempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.tempo')),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='dias',
            field=models.ManyToManyField(to='cadastro.diatempopermitido'),
        ),
    ]
