# Generated by Django 5.2.5 on 2025-11-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_tempo_options_remove_turma_dias_proibidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinas',
            name='dias_proibidos',
        ),
        migrations.AlterField(
            model_name='professor',
            name='dias_proibidos',
            field=models.ManyToManyField(to='cadastro.diatempopermitido'),
        ),
    ]
