# Generated by Django 5.2.5 on 2025-11-30 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_remove_disciplinas_dias_proibidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='horarios',
            field=models.ManyToManyField(blank=True, to='cadastro.diatempopermitido'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='dia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='tempo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.tempo'),
        ),
    ]
