# Generated by Django 5.2.5 on 2025-11-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_aula_horarios_alter_aula_dia_alter_aula_tempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('periodos', models.PositiveIntegerField()),
                ('abreviatura', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.curso'),
        ),
    ]
